version: "3"
   
services:
  code-api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - env
  db:
    image: postgres:13
    volumes:
      # - ./.db:/var/lib/postgresql/data
      # - ./.db2:/var/lib/postgresql/data
      - ./.db4:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABSE_NAME:-codeapi}
      - POSTGRES_USER=${DATABSE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABSE_PASS:-postgres}