version: "3"
   
services:
  code-api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - env
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABSE_NAME:-postgres}
      - POSTGRES_USER=${DATABSE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABSE_PASS:-postgres}