version: "3"
   
services:
  django-rest-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:13
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABSE_NAME:-codedb}
      - POSTGRES_USER=${DATABSE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABSE_PASS:-postgres}
    ports:
      - "5432:5432"